name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t flask-app:latest .

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 flask-app:latest

    - name: Test the app
      run: |
        curl --fail http://localhost:5000
